 LU Benchmark Completed.
 Class           =                        A
 Size            =             64x  64x  64
 Iterations      =                      250
 Time in seconds =                     8.90
 Total processes =                      128
 Compiled procs  =                      128
 Mop/s total     =                 13398.42
 Mop/s/process   =                   104.68
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 12:40
real 16.125	user 13.997	sys 0.756	pcpu 91.49
