 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    26.19
 Total processes =                       16
 Compiled procs  =                       16
 Mop/s total     =                 19045.75
 Mop/s/process   =                  1190.36
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 14:32
