/* !!!!! This file is automatically generated by a wrapper-engine !!!!! */


#include "umpi_internal.h"

void umpi_print_op_MPI_Abort(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\terrorcode = %i\n", op->data.mpi.errorcode);
return;
}
void umpi_print_op_MPI_Address(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tlocation = %i\n", op->data.mpi.location);
sprintf(buf+strlen(buf),"\taddress = %i\n", op->data.mpi.address);
return;
}
void umpi_print_op_MPI_Allgather(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);
sprintf(buf+strlen(buf),"\trecvcount = %i\n", op->data.mpi.recvcount);
sprintf(buf+strlen(buf),"\trecvtype = %i\n", op->data.mpi.recvtype);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Allgatherv(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);

sprintf(buf+strlen(buf),"\trecvcounts = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.recvcounts[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tdispls = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.displs[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\trecvtype = %i\n", op->data.mpi.recvtype);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Allreduce(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\top = %i\n", op->data.mpi.op);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Alltoall(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);
sprintf(buf+strlen(buf),"\trecvcount = %i\n", op->data.mpi.recvcount);
sprintf(buf+strlen(buf),"\trecvtype = %i\n", op->data.mpi.recvtype);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Alltoallv(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);

sprintf(buf+strlen(buf),"\tcounts = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.counts[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tsdispls = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.sdispls[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);

sprintf(buf+strlen(buf),"\trecvcounts = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.recvcounts[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\trdispls = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.rdispls[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\trecvtype = %i\n", op->data.mpi.recvtype);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Attr_delete(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tkeyval = %i\n", op->data.mpi.keyval);
return;
}
void umpi_print_op_MPI_Attr_get(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tkeyval = %i\n", op->data.mpi.keyval);
sprintf(buf+strlen(buf),"\tattr_value = %i\n", op->data.mpi.attr_value);
sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
return;
}
void umpi_print_op_MPI_Attr_put(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tkeyval = %i\n", op->data.mpi.keyval);
sprintf(buf+strlen(buf),"\tattr_value = %i\n", op->data.mpi.attr_value);
return;
}
void umpi_print_op_MPI_Barrier(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Bcast(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\troot = %i\n", op->data.mpi.root);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Bsend(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Bsend_init(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Buffer_attach(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Buffer_detach(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbufptr = %i\n", op->data.mpi.bufptr);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Cancel(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Cart_coords(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trank = %i\n", op->data.mpi.rank);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_coords = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_coords[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Cart_create(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_dims = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_dims[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_periods = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_periods[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\treorder = %i\n", op->data.mpi.reorder);
sprintf(buf+strlen(buf),"\tcomm_out = %i\n", op->data.mpi.comm_out);
return;
}
void umpi_print_op_MPI_Cart_get(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_dims = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_dims[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_periods = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_periods[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_coords = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_coords[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Cart_map(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_dims = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_dims[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_periods = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_periods[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tnewrank = %i\n", op->data.mpi.newrank);
return;
}
void umpi_print_op_MPI_Cart_rank(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);

sprintf(buf+strlen(buf),"\tretcoords = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.retcoords[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\trank = %i\n", op->data.mpi.rank);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Cart_shift(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tdirection = %i\n", op->data.mpi.direction);
sprintf(buf+strlen(buf),"\tdispl = %i\n", op->data.mpi.displ);
sprintf(buf+strlen(buf),"\tcart_src = %i\n", op->data.mpi.cart_src);
sprintf(buf+strlen(buf),"\tcart_dest = %i\n", op->data.mpi.cart_dest);
return;
}
void umpi_print_op_MPI_Cart_sub(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);

sprintf(buf+strlen(buf),"\tdimsp = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.dimsp[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tcomm_out = %i\n", op->data.mpi.comm_out);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Cartdim_get(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tndims_p = %i\n", op->data.mpi.ndims_p);
return;
}
void umpi_print_op_MPI_Comm_compare(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm1 = %i\n", op->data.mpi.comm1);
sprintf(buf+strlen(buf),"\tcomm2 = %i\n", op->data.mpi.comm2);
sprintf(buf+strlen(buf),"\tresult = %i\n", op->data.mpi.result);
return;
}
void umpi_print_op_MPI_Comm_create(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tgroup = %i\n", op->data.mpi.group);
sprintf(buf+strlen(buf),"\tcomm_out = %i\n", op->data.mpi.comm_out);
return;
}
void umpi_print_op_MPI_Comm_dup(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tcomm_out = %i\n", op->data.mpi.comm_out);
return;
}
void umpi_print_op_MPI_Comm_free(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcommp = %i\n", op->data.mpi.commp);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Comm_get_name(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tnamep = %i\n", op->data.mpi.namep);
sprintf(buf+strlen(buf),"\treslen = %i\n", op->data.mpi.reslen);
return;
}
void umpi_print_op_MPI_Comm_group(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tgroup_out = %i\n", op->data.mpi.group_out);
return;
}
void umpi_print_op_MPI_Comm_rank(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trank = %i\n", op->data.mpi.rank);
return;
}
void umpi_print_op_MPI_Comm_remote_group(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tgroup_out = %i\n", op->data.mpi.group_out);
return;
}
void umpi_print_op_MPI_Comm_remote_size(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Comm_set_name(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tname = %i\n", op->data.mpi.name);
return;
}
void umpi_print_op_MPI_Comm_size(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Comm_split(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tcolor = %i\n", op->data.mpi.color);
sprintf(buf+strlen(buf),"\tkey = %i\n", op->data.mpi.key);
sprintf(buf+strlen(buf),"\tcomm_out = %i\n", op->data.mpi.comm_out);
return;
}
void umpi_print_op_MPI_Comm_test_inter(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
return;
}
void umpi_print_op_MPI_Dims_create(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tnnodes = %i\n", op->data.mpi.nnodes);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_dims = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_dims[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Errhandler_create(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tfunction = %i\n", op->data.mpi.function);
sprintf(buf+strlen(buf),"\terrhandler = %i\n", op->data.mpi.errhandler);
return;
}
void umpi_print_op_MPI_Errhandler_free(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\terrhandler = %i\n", op->data.mpi.errhandler);
return;
}
void umpi_print_op_MPI_Errhandler_get(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\terrhandler = %i\n", op->data.mpi.errhandler);
return;
}
void umpi_print_op_MPI_Errhandler_set(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\terrhandler_notptr = %i\n", op->data.mpi.errhandler_notptr);
return;
}
void umpi_print_op_MPI_Error_class(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\terrorcode = %i\n", op->data.mpi.errorcode);
sprintf(buf+strlen(buf),"\terrorclass = %i\n", op->data.mpi.errorclass);
return;
}
void umpi_print_op_MPI_Error_string(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\terrorcode = %i\n", op->data.mpi.errorcode);
sprintf(buf+strlen(buf),"\tstring = %i\n", op->data.mpi.string);
sprintf(buf+strlen(buf),"\treslen = %i\n", op->data.mpi.reslen);
return;
}
void umpi_print_op_MPI_Finalize(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
return;
}
void umpi_print_op_MPI_Finalized(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
return;
}
void umpi_print_op_MPI_Gather(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);
sprintf(buf+strlen(buf),"\trecvcount = %i\n", op->data.mpi.recvcount);
sprintf(buf+strlen(buf),"\trecvtype = %i\n", op->data.mpi.recvtype);
sprintf(buf+strlen(buf),"\troot = %i\n", op->data.mpi.root);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Gatherv(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);

sprintf(buf+strlen(buf),"\trecvcounts = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.recvcounts[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tdispls = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.displs[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\trecvtype = %i\n", op->data.mpi.recvtype);
sprintf(buf+strlen(buf),"\troot = %i\n", op->data.mpi.root);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Get_count(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tcountp = %i\n", op->data.mpi.countp);
sprintf(buf+strlen(buf),"\tstatus_src = %i\n", op->data.mpi.status_src);
sprintf(buf+strlen(buf),"\tstatuses_srcs = %i\n", op->data.mpi.statuses_srcs);
return;
}
void umpi_print_op_MPI_Get_elements(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\telements = %i\n", op->data.mpi.elements);
return;
}
void umpi_print_op_MPI_Get_processor_name(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tname = %i\n", op->data.mpi.name);
sprintf(buf+strlen(buf),"\treslen = %i\n", op->data.mpi.reslen);
return;
}
void umpi_print_op_MPI_Get_version(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tversion = %i\n", op->data.mpi.version);
sprintf(buf+strlen(buf),"\tsubversion = %i\n", op->data.mpi.subversion);
return;
}
void umpi_print_op_MPI_Graph_create(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_degrees = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_degrees[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tedges = [ ");{
int i;
for(i=0;i<op->data.mpi.array_of_degrees[op->data.mpi.count-1];i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.edges[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\treorder = %i\n", op->data.mpi.reorder);
sprintf(buf+strlen(buf),"\tcomm_out = %i\n", op->data.mpi.comm_out);
return;
}
void umpi_print_op_MPI_Graph_get(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tedgecount = %i\n", op->data.mpi.edgecount);

sprintf(buf+strlen(buf),"\tarray_of_degrees = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_degrees[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tretedges = [ ");{
int i;
for(i=0;i<op->data.mpi.edgecount;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.retedges[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Graph_map(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_degrees = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_degrees[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tedges = [ ");{
int i;
for(i=0;i<op->data.mpi.array_of_degrees[op->data.mpi.count-1];i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.edges[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tnewrank = %i\n", op->data.mpi.newrank);
return;
}
void umpi_print_op_MPI_Graph_neighbors(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trank = %i\n", op->data.mpi.rank);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_neighbors = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_neighbors[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Graph_neighbors_count(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trank = %i\n", op->data.mpi.rank);
sprintf(buf+strlen(buf),"\tnneighbors = %i\n", op->data.mpi.nneighbors);
return;
}
void umpi_print_op_MPI_Graphdims_get(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tnnodes = %i\n", op->data.mpi.nnodes);
sprintf(buf+strlen(buf),"\tedgecountp = %i\n", op->data.mpi.edgecountp);
return;
}
void umpi_print_op_MPI_Group_compare(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup1 = %i\n", op->data.mpi.group1);
sprintf(buf+strlen(buf),"\tgroup2 = %i\n", op->data.mpi.group2);
sprintf(buf+strlen(buf),"\tresult = %i\n", op->data.mpi.result);
return;
}
void umpi_print_op_MPI_Group_difference(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup1 = %i\n", op->data.mpi.group1);
sprintf(buf+strlen(buf),"\tgroup2 = %i\n", op->data.mpi.group2);
sprintf(buf+strlen(buf),"\tgroup_out = %i\n", op->data.mpi.group_out);
return;
}
void umpi_print_op_MPI_Group_excl(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup = %i\n", op->data.mpi.group);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_ranks = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_ranks[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tgroup_out = %i\n", op->data.mpi.group_out);
return;
}
void umpi_print_op_MPI_Group_free(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup_out = %i\n", op->data.mpi.group_out);
return;
}
void umpi_print_op_MPI_Group_incl(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup = %i\n", op->data.mpi.group);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_ranks = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_ranks[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tgroup_out = %i\n", op->data.mpi.group_out);
return;
}
void umpi_print_op_MPI_Group_intersection(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup1 = %i\n", op->data.mpi.group1);
sprintf(buf+strlen(buf),"\tgroup2 = %i\n", op->data.mpi.group2);
sprintf(buf+strlen(buf),"\tgroup_out = %i\n", op->data.mpi.group_out);
return;
}
void umpi_print_op_MPI_Group_range_excl(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup = %i\n", op->data.mpi.group);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tranges = \n");{
int i, j;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "\t\t| ");
for(j=0;j<3;j++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.ranges[3*i+j]);
}
sprintf(buf+strlen(buf), "|\n");

}
}
sprintf(buf+strlen(buf),"\tgroup_out = %i\n", op->data.mpi.group_out);
return;
}
void umpi_print_op_MPI_Group_range_incl(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup = %i\n", op->data.mpi.group);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tranges = \n");{
int i, j;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "\t\t| ");
for(j=0;j<3;j++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.ranges[3*i+j]);
}
sprintf(buf+strlen(buf), "|\n");

}
}
sprintf(buf+strlen(buf),"\tgroup_out = %i\n", op->data.mpi.group_out);
return;
}
void umpi_print_op_MPI_Group_rank(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup = %i\n", op->data.mpi.group);
sprintf(buf+strlen(buf),"\trank = %i\n", op->data.mpi.rank);
return;
}
void umpi_print_op_MPI_Group_size(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup = %i\n", op->data.mpi.group);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Group_translate_ranks(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup1 = %i\n", op->data.mpi.group1);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_ranks = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_ranks[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tgroup2 = %i\n", op->data.mpi.group2);

sprintf(buf+strlen(buf),"\tarray_of_ranks2 = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_ranks2[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Group_union(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tgroup1 = %i\n", op->data.mpi.group1);
sprintf(buf+strlen(buf),"\tgroup2 = %i\n", op->data.mpi.group2);
sprintf(buf+strlen(buf),"\tgroup_out = %i\n", op->data.mpi.group_out);
return;
}
void umpi_print_op_MPI_Handle2int(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tc_handle = %i\n", op->data.mpi.c_handle);
sprintf(buf+strlen(buf),"\thandle_kind = %i\n", op->data.mpi.handle_kind);
return;
}
void umpi_print_op_MPI_Ibsend(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Info_c2f(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
return;
}
void umpi_print_op_MPI_Info_create(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
return;
}
void umpi_print_op_MPI_Info_delete(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
sprintf(buf+strlen(buf),"\tkey = %i\n", op->data.mpi.key);
return;
}
void umpi_print_op_MPI_Info_dup(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
sprintf(buf+strlen(buf),"\tnewinfo = %i\n", op->data.mpi.newinfo);
return;
}
void umpi_print_op_MPI_Info_f2c(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
return;
}
void umpi_print_op_MPI_Info_free(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
return;
}
void umpi_print_op_MPI_Info_get(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
sprintf(buf+strlen(buf),"\tkey = %i\n", op->data.mpi.key);
sprintf(buf+strlen(buf),"\tvaluelen = %i\n", op->data.mpi.valuelen);
sprintf(buf+strlen(buf),"\tvalue = %i\n", op->data.mpi.value);
sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
return;
}
void umpi_print_op_MPI_Info_get_nkeys(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
sprintf(buf+strlen(buf),"\tnkeys = %i\n", op->data.mpi.nkeys);
return;
}
void umpi_print_op_MPI_Info_get_nthkey(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tkey = %i\n", op->data.mpi.key);
return;
}
void umpi_print_op_MPI_Info_get_valuelen(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
sprintf(buf+strlen(buf),"\tkey = %i\n", op->data.mpi.key);
sprintf(buf+strlen(buf),"\tvaluelen = %i\n", op->data.mpi.valuelen);
sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
return;
}
void umpi_print_op_MPI_Info_set(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinfo = %i\n", op->data.mpi.info);
sprintf(buf+strlen(buf),"\tkey = %i\n", op->data.mpi.key);
sprintf(buf+strlen(buf),"\tvalue = %i\n", op->data.mpi.value);
return;
}
void umpi_print_op_MPI_Init(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\targc = %i\n", op->data.mpi.argc);
sprintf(buf+strlen(buf),"\targv = %i\n", op->data.mpi.argv);
return;
}
void umpi_print_op_MPI_Initialized(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
return;
}
void umpi_print_op_MPI_Int2handle(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tf_handle = %i\n", op->data.mpi.f_handle);
sprintf(buf+strlen(buf),"\thandle_kind = %i\n", op->data.mpi.handle_kind);
return;
}
void umpi_print_op_MPI_Intercomm_create(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tlocal_leader = %i\n", op->data.mpi.local_leader);
sprintf(buf+strlen(buf),"\tpeer_comm = %i\n", op->data.mpi.peer_comm);
sprintf(buf+strlen(buf),"\tremote_leader = %i\n", op->data.mpi.remote_leader);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm_out = %i\n", op->data.mpi.comm_out);
sprintf(buf+strlen(buf),"\tcomm1 = %i\n", op->data.mpi.comm1);
return;
}
void umpi_print_op_MPI_Intercomm_merge(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\thigh = %i\n", op->data.mpi.high);
sprintf(buf+strlen(buf),"\tcomm_out = %i\n", op->data.mpi.comm_out);
return;
}
void umpi_print_op_MPI_Iprobe(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tsource = %i\n", op->data.mpi.source);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
return;
}
void umpi_print_op_MPI_Irecv(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tsource = %i\n", op->data.mpi.source);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Irsend(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Isend(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Issend(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Keyval_create(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcopy_function = %i\n", op->data.mpi.copy_function);
sprintf(buf+strlen(buf),"\tdelete_function = %i\n", op->data.mpi.delete_function);
sprintf(buf+strlen(buf),"\tkeyval = %i\n", op->data.mpi.keyval);
sprintf(buf+strlen(buf),"\textra_state = %i\n", op->data.mpi.extra_state);
return;
}
void umpi_print_op_MPI_Keyval_free(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tkeyval = %i\n", op->data.mpi.keyval);
return;
}
void umpi_print_op_MPI_Op_create(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tfunction = %i\n", op->data.mpi.function);
sprintf(buf+strlen(buf),"\tcommute = %i\n", op->data.mpi.commute);
sprintf(buf+strlen(buf),"\top = %i\n", op->data.mpi.op);
sprintf(buf+strlen(buf),"\top_ptr = %i\n", op->data.mpi.op_ptr);
return;
}
void umpi_print_op_MPI_Op_free(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\top = %i\n", op->data.mpi.op);
sprintf(buf+strlen(buf),"\top_ptr = %i\n", op->data.mpi.op_ptr);
return;
}
void umpi_print_op_MPI_Pack(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinbuf = %i\n", op->data.mpi.inbuf);
sprintf(buf+strlen(buf),"\tincount = %i\n", op->data.mpi.incount);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\toutbuf = %i\n", op->data.mpi.outbuf);
sprintf(buf+strlen(buf),"\toutcount = %i\n", op->data.mpi.outcount);
sprintf(buf+strlen(buf),"\tposition = %i\n", op->data.mpi.position);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Pack_size(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tincount = %i\n", op->data.mpi.incount);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Pcontrol(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tlevel = %i\n", op->data.mpi.level);
return;
}
void umpi_print_op_MPI_Probe(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tsource = %i\n", op->data.mpi.source);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
return;
}
void umpi_print_op_MPI_Recv(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tsource = %i\n", op->data.mpi.source);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
return;
}
void umpi_print_op_MPI_Recv_init(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tsource = %i\n", op->data.mpi.source);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Reduce(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\top = %i\n", op->data.mpi.op);
sprintf(buf+strlen(buf),"\troot = %i\n", op->data.mpi.root);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Reduce_scatter(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);

sprintf(buf+strlen(buf),"\trecvcounts = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.recvcounts[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\top = %i\n", op->data.mpi.op);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Request_c2f(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tc_request = %i\n", op->data.mpi.c_request);
return;
}
void umpi_print_op_MPI_Request_free(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Rsend(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Rsend_init(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Scan(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\top = %i\n", op->data.mpi.op);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Scatter(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);
sprintf(buf+strlen(buf),"\trecvcount = %i\n", op->data.mpi.recvcount);
sprintf(buf+strlen(buf),"\trecvtype = %i\n", op->data.mpi.recvtype);
sprintf(buf+strlen(buf),"\troot = %i\n", op->data.mpi.root);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Scatterv(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);

sprintf(buf+strlen(buf),"\tcounts = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.counts[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tdispls = [ ");{
int i;
for(i=0;i<op->data.mpi.size;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.displs[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);
sprintf(buf+strlen(buf),"\trecvcount = %i\n", op->data.mpi.recvcount);
sprintf(buf+strlen(buf),"\trecvtype = %i\n", op->data.mpi.recvtype);
sprintf(buf+strlen(buf),"\troot = %i\n", op->data.mpi.root);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Send(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Send_init(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Sendrecv(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\tsendtag = %i\n", op->data.mpi.sendtag);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);
sprintf(buf+strlen(buf),"\trecvcount = %i\n", op->data.mpi.recvcount);
sprintf(buf+strlen(buf),"\trecvtype = %i\n", op->data.mpi.recvtype);
sprintf(buf+strlen(buf),"\tsource = %i\n", op->data.mpi.source);
sprintf(buf+strlen(buf),"\trecvtag = %i\n", op->data.mpi.recvtag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
return;
}
void umpi_print_op_MPI_Sendrecv_replace(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\tsendtag = %i\n", op->data.mpi.sendtag);
sprintf(buf+strlen(buf),"\tsource = %i\n", op->data.mpi.source);
sprintf(buf+strlen(buf),"\trecvtag = %i\n", op->data.mpi.recvtag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
sprintf(buf+strlen(buf),"\trecvbuf = %i\n", op->data.mpi.recvbuf);
sprintf(buf+strlen(buf),"\trecvcount = %i\n", op->data.mpi.recvcount);
sprintf(buf+strlen(buf),"\trecvtype = %i\n", op->data.mpi.recvtype);
return;
}
void umpi_print_op_MPI_Ssend(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Ssend_init(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tbuf = %i\n", op->data.mpi.buf);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdest = %i\n", op->data.mpi.dest);
sprintf(buf+strlen(buf),"\ttag = %i\n", op->data.mpi.tag);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Start(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
return;
}
void umpi_print_op_MPI_Startall(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_requests = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_requests[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Status_c2f(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tc_status = %i\n", op->data.mpi.c_status);
sprintf(buf+strlen(buf),"\tf_status = %i\n", op->data.mpi.f_status);
return;
}
void umpi_print_op_MPI_Status_f2c(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tf_status = %i\n", op->data.mpi.f_status);
sprintf(buf+strlen(buf),"\tc_status = %i\n", op->data.mpi.c_status);
return;
}
void umpi_print_op_MPI_Test(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
return;
}
void umpi_print_op_MPI_Test_cancelled(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
return;
}
void umpi_print_op_MPI_Testall(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_requests = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_requests[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);

sprintf(buf+strlen(buf),"\tarray_of_statuses[].MPI_SOURCE = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.statuses_srcs[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Testany(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_requests = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_requests[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tindex = %i\n", op->data.mpi.index);
sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
return;
}
void umpi_print_op_MPI_Testsome(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_requests = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_requests[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\toutcount = %i\n", op->data.mpi.outcount);

sprintf(buf+strlen(buf),"\tarray_of_indices = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_indices[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_statuses[].MPI_SOURCE = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.statuses_srcs[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tflag = %i\n", op->data.mpi.flag);
return;
}
void umpi_print_op_MPI_Topo_test(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
sprintf(buf+strlen(buf),"\ttop_type = %i\n", op->data.mpi.top_type);
return;
}
void umpi_print_op_MPI_Type_commit(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Type_contiguous(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\told_type = %i\n", op->data.mpi.old_type);
sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Type_count(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
return;
}
void umpi_print_op_MPI_Type_create_darray(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
sprintf(buf+strlen(buf),"\trank = %i\n", op->data.mpi.rank);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_gsizes = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_gsizes[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_distribs = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_distribs[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_dargs = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_dargs[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_psizes = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_psizes[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\torder = %i\n", op->data.mpi.order);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Type_create_indexed_block(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tblocklength = %i\n", op->data.mpi.blocklength);

sprintf(buf+strlen(buf),"\tarray_of_displacements = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_displacements[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Type_create_subarray(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_sizes = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_sizes[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_subsizes = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_subsizes[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_starts = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_starts[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\torder = %i\n", op->data.mpi.order);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Type_extent(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\textent = %i\n", op->data.mpi.extent);
return;
}
void umpi_print_op_MPI_Type_free(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Type_get_contents(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\taddrcount = %i\n", op->data.mpi.addrcount);
sprintf(buf+strlen(buf),"\tdtypecount = %i\n", op->data.mpi.dtypecount);

sprintf(buf+strlen(buf),"\tarray_of_integers = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_integers[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tthe_addresses = [ ");{
int i;
for(i=0;i<op->data.mpi.addrcount;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.the_addresses[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tthe_datatypes = [ ");{
int i;
for(i=0;i<op->data.mpi.dtypecount;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.the_datatypes[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Type_get_envelope(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tnum_integers = %i\n", op->data.mpi.num_integers);
sprintf(buf+strlen(buf),"\tnum_addresses = %i\n", op->data.mpi.num_addresses);
sprintf(buf+strlen(buf),"\tnum_datatypes = %i\n", op->data.mpi.num_datatypes);
sprintf(buf+strlen(buf),"\tcombiner = %i\n", op->data.mpi.combiner);
return;
}
void umpi_print_op_MPI_Type_hindexed(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_blocklens = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_blocklens[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_displacements = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_displacements[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Type_hvector(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tblocklen = %i\n", op->data.mpi.blocklen);
sprintf(buf+strlen(buf),"\tstride = %i\n", op->data.mpi.stride);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Type_indexed(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_blocklens = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_blocklens[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_displacements = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_displacements[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Type_lb(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdisplacement = %i\n", op->data.mpi.displacement);
return;
}
void umpi_print_op_MPI_Type_size(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tsize = %i\n", op->data.mpi.size);
return;
}
void umpi_print_op_MPI_Type_struct(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_blocklens = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_blocklens[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_displacements = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_displacements[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_types = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_types[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Type_ub(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tdisplacement = %i\n", op->data.mpi.displacement);
return;
}
void umpi_print_op_MPI_Type_vector(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);
sprintf(buf+strlen(buf),"\tblocklen = %i\n", op->data.mpi.blocklen);
sprintf(buf+strlen(buf),"\tstride = %i\n", op->data.mpi.stride);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tnewtype = %i\n", op->data.mpi.newtype);
return;
}
void umpi_print_op_MPI_Unpack(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tinbuf = %i\n", op->data.mpi.inbuf);
sprintf(buf+strlen(buf),"\tinsize = %i\n", op->data.mpi.insize);
sprintf(buf+strlen(buf),"\tposition = %i\n", op->data.mpi.position);
sprintf(buf+strlen(buf),"\toutbuf = %i\n", op->data.mpi.outbuf);
sprintf(buf+strlen(buf),"\toutcount = %i\n", op->data.mpi.outcount);
sprintf(buf+strlen(buf),"\tdatatype = %i\n", op->data.mpi.datatype);
sprintf(buf+strlen(buf),"\tcomm = %i\n", op->data.mpi.comm);
return;
}
void umpi_print_op_MPI_Wait(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\trequest = %i\n", op->data.mpi.request);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
return;
}
void umpi_print_op_MPI_Waitall(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_requests = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_requests[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_statuses[].MPI_SOURCE = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.statuses_srcs[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Waitany(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_requests = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_requests[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\tindex = %i\n", op->data.mpi.index);
sprintf(buf+strlen(buf),"\tstatus->MPI_SOURCE = %i\n", op->data.mpi.status_src);
return;
}
void umpi_print_op_MPI_Waitsome(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
sprintf(buf+strlen(buf),"\tcount = %i\n", op->data.mpi.count);

sprintf(buf+strlen(buf),"\tarray_of_requests = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_requests[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

sprintf(buf+strlen(buf),"\toutcount = %i\n", op->data.mpi.outcount);

sprintf(buf+strlen(buf),"\tarray_of_indices = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.array_of_indices[i]);
}
}
sprintf(buf+strlen(buf), "]\n");


sprintf(buf+strlen(buf),"\tarray_of_statuses[].MPI_SOURCE = [ ");{
int i;
for(i=0;i<op->data.mpi.count;i++) {
sprintf(buf+strlen(buf), "%i ", op->data.mpi.statuses_srcs[i]);
}
}
sprintf(buf+strlen(buf), "]\n");

return;
}
void umpi_print_op_MPI_Wtick(umpi_op_t*op,char *buf)
{
assert(op);
assert(buf);
sprintf(buf, "%d/%d/%x: %d %s %s \n", op->rank, op->seq_num, op->pc,op->op, (get_struct_by_opcode(op->op))->name, ((op->order==umpi_preop)?"pre":"pos"));
sprintf(buf+strlen(buf),"\tumpi_op_ref_count = %i\n", op->umpi_op_ref_count);
return;
}
void umpi_print_op_MPI_Wtime(umpi_