/* !!!!! This file is automatically generated by a wrapper-engine !!!!! */


#include "umpi_internal.h"

void
umpi_free_op_MPI_Allgatherv(umpi_op_t*op)
{
if (op->data.mpi.recvcounts != NULL) {
free (op->data.mpi.recvcounts);
op->data.mpi.recvcounts = NULL;
}

if (op->data.mpi.displs != NULL) {
free (op->data.mpi.displs);
op->data.mpi.displs = NULL;
}

return;
} /* umpi_free_op_MPI_Allgatherv */


void
umpi_free_op_MPI_Alltoallv(umpi_op_t*op)
{
if (op->data.mpi.counts != NULL) {
free (op->data.mpi.counts);
op->data.mpi.counts = NULL;
}

if (op->data.mpi.sdispls != NULL) {
free (op->data.mpi.sdispls);
op->data.mpi.sdispls = NULL;
}

if (op->data.mpi.recvcounts != NULL) {
free (op->data.mpi.recvcounts);
op->data.mpi.recvcounts = NULL;
}

if (op->data.mpi.rdispls != NULL) {
free (op->data.mpi.rdispls);
op->data.mpi.rdispls = NULL;
}

return;
} /* umpi_free_op_MPI_Alltoallv */


void
umpi_free_op_MPI_Cart_coords(umpi_op_t*op)
{
if (op->data.mpi.array_of_coords != NULL) {
free (op->data.mpi.array_of_coords);
op->data.mpi.array_of_coords = NULL;
}

return;
} /* umpi_free_op_MPI_Cart_coords */


void
umpi_free_op_MPI_Cart_create(umpi_op_t*op)
{
if (op->data.mpi.array_of_dims != NULL) {
free (op->data.mpi.array_of_dims);
op->data.mpi.array_of_dims = NULL;
}

if (op->data.mpi.array_of_periods != NULL) {
free (op->data.mpi.array_of_periods);
op->data.mpi.array_of_periods = NULL;
}

return;
} /* umpi_free_op_MPI_Cart_create */


void
umpi_free_op_MPI_Cart_get(umpi_op_t*op)
{
if (op->data.mpi.array_of_dims != NULL) {
free (op->data.mpi.array_of_dims);
op->data.mpi.array_of_dims = NULL;
}

if (op->data.mpi.array_of_periods != NULL) {
free (op->data.mpi.array_of_periods);
op->data.mpi.array_of_periods = NULL;
}

if (op->data.mpi.array_of_coords != NULL) {
free (op->data.mpi.array_of_coords);
op->data.mpi.array_of_coords = NULL;
}

return;
} /* umpi_free_op_MPI_Cart_get */


void
umpi_free_op_MPI_Cart_map(umpi_op_t*op)
{
if (op->data.mpi.array_of_dims != NULL) {
free (op->data.mpi.array_of_dims);
op->data.mpi.array_of_dims = NULL;
}

if (op->data.mpi.array_of_periods != NULL) {
free (op->data.mpi.array_of_periods);
op->data.mpi.array_of_periods = NULL;
}

return;
} /* umpi_free_op_MPI_Cart_map */


void
umpi_free_op_MPI_Cart_rank(umpi_op_t*op)
{
if (op->data.mpi.retcoords != NULL) {
free (op->data.mpi.retcoords);
op->data.mpi.retcoords = NULL;
}

return;
} /* umpi_free_op_MPI_Cart_rank */


void
umpi_free_op_MPI_Cart_sub(umpi_op_t*op)
{
if (op->data.mpi.dimsp != NULL) {
free (op->data.mpi.dimsp);
op->data.mpi.dimsp = NULL;
}

return;
} /* umpi_free_op_MPI_Cart_sub */


void
umpi_free_op_MPI_Dims_create(umpi_op_t*op)
{
if (op->data.mpi.array_of_dims != NULL) {
free (op->data.mpi.array_of_dims);
op->data.mpi.array_of_dims = NULL;
}

return;
} /* umpi_free_op_MPI_Dims_create */


void
umpi_free_op_MPI_Gatherv(umpi_op_t*op)
{
if (op->data.mpi.recvcounts != NULL) {
free (op->data.mpi.recvcounts);
op->data.mpi.recvcounts = NULL;
}

if (op->data.mpi.displs != NULL) {
free (op->data.mpi.displs);
op->data.mpi.displs = NULL;
}

return;
} /* umpi_free_op_MPI_Gatherv */


void
umpi_free_op_MPI_Graph_create(umpi_op_t*op)
{
if (op->data.mpi.array_of_degrees != NULL) {
free (op->data.mpi.array_of_degrees);
op->data.mpi.array_of_degrees = NULL;
}

if (op->data.mpi.edges != NULL) {
free (op->data.mpi.edges);
op->data.mpi.edges = NULL;
}

return;
} /* umpi_free_op_MPI_Graph_create */


void
umpi_free_op_MPI_Graph_get(umpi_op_t*op)
{
if (op->data.mpi.array_of_degrees != NULL) {
free (op->data.mpi.array_of_degrees);
op->data.mpi.array_of_degrees = NULL;
}

if (op->data.mpi.retedges != NULL) {
free (op->data.mpi.retedges);
op->data.mpi.retedges = NULL;
}

return;
} /* umpi_free_op_MPI_Graph_get */


void
umpi_free_op_MPI_Graph_map(umpi_op_t*op)
{
if (op->data.mpi.array_of_degrees != NULL) {
free (op->data.mpi.array_of_degrees);
op->data.mpi.array_of_degrees = NULL;
}

if (op->data.mpi.edges != NULL) {
free (op->data.mpi.edges);
op->data.mpi.edges = NULL;
}

return;
} /* umpi_free_op_MPI_Graph_map */


void
umpi_free_op_MPI_Graph_neighbors(umpi_op_t*op)
{
if (op->data.mpi.array_of_neighbors != NULL) {
free (op->data.mpi.array_of_neighbors);
op->data.mpi.array_of_neighbors = NULL;
}

return;
} /* umpi_free_op_MPI_Graph_neighbors */


void
umpi_free_op_MPI_Group_excl(umpi_op_t*op)
{
if (op->data.mpi.array_of_ranks != NULL) {
free (op->data.mpi.array_of_ranks);
op->data.mpi.array_of_ranks = NULL;
}

return;
} /* umpi_free_op_MPI_Group_excl */


void
umpi_free_op_MPI_Group_incl(umpi_op_t*op)
{
if (op->data.mpi.array_of_ranks != NULL) {
free (op->data.mpi.array_of_ranks);
op->data.mpi.array_of_ranks = NULL;
}

return;
} /* umpi_free_op_MPI_Group_incl */


void
umpi_free_op_MPI_Group_range_excl(umpi_op_t*op)
{
if (op->data.mpi.ranges != NULL) {
free (op->data.mpi.ranges);
op->data.mpi.ranges = NULL;
}

return;
} /* umpi_free_op_MPI_Group_range_excl */


void
umpi_free_op_MPI_Group_range_incl(umpi_op_t*op)
{
if (op->data.mpi.ranges != NULL) {
free (op->data.mpi.ranges);
op->data.mpi.ranges = NULL;
}

return;
} /* umpi_free_op_MPI_Group_range_incl */


void
umpi_free_op_MPI_Group_translate_ranks(umpi_op_t*op)
{
if (op->data.mpi.array_of_ranks != NULL) {
free (op->data.mpi.array_of_ranks);
op->data.mpi.array_of_ranks = NULL;
}

if (op->data.mpi.array_of_ranks2 != NULL) {
free (op->data.mpi.array_of_ranks2);
op->data.mpi.array_of_ranks2 = NULL;
}

return;
} /* umpi_free_op_MPI_Group_translate_ranks */


void
umpi_free_op_MPI_Reduce_scatter(umpi_op_t*op)
{
if (op->data.mpi.recvcounts != NULL) {
free (op->data.mpi.recvcounts);
op->data.mpi.recvcounts = NULL;
}

return;
} /* umpi_free_op_MPI_Reduce_scatter */


void
umpi_free_op_MPI_Scatterv(umpi_op_t*op)
{
if (op->data.mpi.counts != NULL) {
free (op->data.mpi.counts);
op->data.mpi.counts = NULL;
}

if (op->data.mpi.displs != NULL) {
free (op->data.mpi.displs);
op->data.mpi.displs = NULL;
}

return;
} /* umpi_free_op_MPI_Scatterv */


void
umpi_free_op_MPI_Startall(umpi_op_t*op)
{
if (op->data.mpi.array_of_requests != NULL) {
free (op->data.mpi.array_of_requests);
op->data.mpi.array_of_requests = NULL;
}

return;
} /* umpi_free_op_MPI_Startall */


void
umpi_free_op_MPI_Testall(umpi_op_t*op)
{
if (op->data.mpi.array_of_requests != NULL) {
free (op->data.mpi.array_of_requests);
op->data.mpi.array_of_requests = NULL;
}

if (op->data.mpi.statuses_srcs != NULL) {
free (op->data.mpi.statuses_srcs);
op->data.mpi.statuses_srcs = NULL;
}

return;
} /* umpi_free_op_MPI_Testall */


void
umpi_free_op_MPI_Testany(umpi_op_t*op)
{
if (op->data.mpi.array_of_requests != NULL) {
free (op->data.mpi.array_of_requests);
op->data.mpi.array_of_requests = NULL;
}

return;
} /* umpi_free_op_MPI_Testany */


void
umpi_free_op_MPI_Testsome(umpi_op_t*op)
{
if (op->data.mpi.array_of_requests != NULL) {
free (op->data.mpi.array_of_requests);
op->data.mpi.array_of_requests = NULL;
}

if (op->data.mpi.array_of_indices != NULL) {
free (op->data.mpi.array_of_indices);
op->data.mpi.array_of_indices = NULL;
}

if (op->data.mpi.statuses_srcs != NULL) {
free (op->data.mpi.statuses_srcs);
op->data.mpi.statuses_srcs = NULL;
}

return;
} /* umpi_free_op_MPI_Testsome */


void
umpi_free_op_MPI_Type_create_darray(umpi_op_t*op)
{
if (op->data.mpi.array_of_gsizes != NULL) {
free (op->data.mpi.array_of_gsizes);
op->data.mpi.array_of_gsizes = NULL;
}

if (op->data.mpi.array_of_distribs != NULL) {
free (op->data.mpi.array_of_distribs);
op->data.mpi.array_of_distribs = NULL;
}

if (op->data.mpi.array_of_dargs != NULL) {
free (op->data.mpi.array_of_dargs);
op->data.mpi.array_of_dargs = NULL;
}

if (op->data.mpi.array_of_psizes != NULL) {
free (op->data.mpi.array_of_psizes);
op->data.mpi.array_of_psizes = NULL;
}

return;
} /* umpi_free_op_MPI_Type_create_darray */


void
umpi_free_op_MPI_Type_create_indexed_block(umpi_op_t*op)
{
if (op->data.mpi.array_of_displacements != NULL) {
free (op->data.mpi.array_of_displacements);
op->data.mpi.array_of_displacements = NULL;
}

return;
} /* umpi_free_op_MPI_Type_create_indexed_block */


void
umpi_free_op_MPI_Type_create_subarray(umpi_op_t*op)
{
if (op->data.mpi.array_of_sizes != NULL) {
free (op->data.mpi.array_of_sizes);
op->data.mpi.array_o