/* Umpire lookup table struct header file */

/* !!!!! This file is automatically generated by a wrapper-engine !!!!! */



#ifndef _UMPI_MPI_H
#define _UMPI_MPI_H



#define umpi_MPI_Abort 1000
#define umpi_MPI_Address 1001
#define umpi_MPI_Allgather 1002
#define umpi_MPI_Allgatherv 1003
#define umpi_MPI_Allreduce 1004
#define umpi_MPI_Alltoall 1005
#define umpi_MPI_Alltoallv 1006
#define umpi_MPI_Attr_delete 1007
#define umpi_MPI_Attr_get 1008
#define umpi_MPI_Attr_put 1009
#define umpi_MPI_Barrier 1010
#define umpi_MPI_Bcast 1011
#define umpi_MPI_Bsend 1012
#define umpi_MPI_Bsend_init 1013
#define umpi_MPI_Buffer_attach 1014
#define umpi_MPI_Buffer_detach 1015
#define umpi_MPI_Cancel 1016
#define umpi_MPI_Cart_coords 1017
#define umpi_MPI_Cart_create 1018
#define umpi_MPI_Cart_get 1019
#define umpi_MPI_Cart_map 1020
#define umpi_MPI_Cart_rank 1021
#define umpi_MPI_Cart_shift 1022
#define umpi_MPI_Cart_sub 1023
#define umpi_MPI_Cartdim_get 1024
#define umpi_MPI_Comm_compare 1025
#define umpi_MPI_Comm_create 1026
#define umpi_MPI_Comm_dup 1027
#define umpi_MPI_Comm_free 1028
#define umpi_MPI_Comm_get_name 1029
#define umpi_MPI_Comm_group 1030
#define umpi_MPI_Comm_rank 1031
#define umpi_MPI_Comm_remote_group 1032
#define umpi_MPI_Comm_remote_size 1033
#define umpi_MPI_Comm_set_name 1034
#define umpi_MPI_Comm_size 1035
#define umpi_MPI_Comm_split 1036
#define umpi_MPI_Comm_test_inter 1037
#define umpi_MPI_Dims_create 1038
#define umpi_MPI_Errhandler_create 1039
#define umpi_MPI_Errhandler_free 1040
#define umpi_MPI_Errhandler_get 1041
#define umpi_MPI_Errhandler_set 1042
#define umpi_MPI_Error_class 1043
#define umpi_MPI_Error_string 1044
#define umpi_MPI_Finalize 1045
#define umpi_MPI_Finalized 1046
#define umpi_MPI_Gather 1047
#define umpi_MPI_Gatherv 1048
#define umpi_MPI_Get_count 1049
#define umpi_MPI_Get_elements 1050
#define umpi_MPI_Get_processor_name 1051
#define umpi_MPI_Get_version 1052
#define umpi_MPI_Graph_create 1053
#define umpi_MPI_Graph_get 1054
#define umpi_MPI_Graph_map 1055
#define umpi_MPI_Graph_neighbors 1056
#define umpi_MPI_Graph_neighbors_count 1057
#define umpi_MPI_Graphdims_get 1058
#define umpi_MPI_Group_compare 1059
#define umpi_MPI_Group_difference 1060
#define umpi_MPI_Group_excl 1061
#define umpi_MPI_Group_free 1062
#define umpi_MPI_Group_incl 1063
#define umpi_MPI_Group_intersection 1064
#define umpi_MPI_Group_range_excl 1065
#define umpi_MPI_Group_range_incl 1066
#define umpi_MPI_Group_rank 1067
#define umpi_MPI_Group_size 1068
#define umpi_MPI_Group_translate_ranks 1069
#define umpi_MPI_Group_union 1070
#define umpi_MPI_Handle2int 1071
#define umpi_MPI_Ibsend 1072
#define umpi_MPI_Info_c2f 1073
#define umpi_MPI_Info_create 1074
#define umpi_MPI_Info_delete 1075
#define umpi_MPI_Info_dup 1076
#define umpi_MPI_Info_f2c 1077
#define umpi_MPI_Info_free 1078
#define umpi_MPI_Info_get 1079
#define umpi_MPI_Info_get_nkeys 1080
#define umpi_MPI_Info_get_nthkey 1081
#define umpi_MPI_Info_get_valuelen 1082
#define umpi_MPI_Info_set 1083
#define umpi_MPI_Init 1084
#define umpi_MPI_Initialized 1085
#define umpi_MPI_Int2handle 1086
#define umpi_MPI_Intercomm_create 1087
#define umpi_MPI_Intercomm_merge 1088
#define umpi_MPI_Iprobe 1089
#define umpi_MPI_Irecv 1090
#define umpi_MPI_Irsend 1091
#define umpi_MPI_Isend 1092
#define umpi_MPI_Issend 1093
#define umpi_MPI_Keyval_create 1094
#define umpi_MPI_Keyval_free 1095
#define umpi_MPI_Op_create 1096
#define umpi_MPI_Op_free 1097
#define umpi_MPI_Pack 1098
#define umpi_MPI_Pack_size 1099
#define umpi_MPI_Pcontrol 1100
#define umpi_MPI_Probe 1101
#define umpi_MPI_Recv 1102
#define umpi_MPI_Recv_init 1103
#define umpi_MPI_Reduce 1104
#define umpi_MPI_Reduce_scatter 1105
#define umpi_MPI_Request_c2f 1106
#define umpi_MPI_Request_free 1107
#define umpi_MPI_Rsend 1108
#define umpi_MPI_Rsend_init 1109
#define umpi_MPI_Scan 1110
#define umpi_MPI_Scatter 1111
#define umpi_MPI_Scatterv 1112
#define umpi_MPI_Send 1113
#define umpi_MPI_Send_init 1114
#define umpi_MPI_Sendrecv 1115
#define umpi_MPI_Sendrecv_replace 1116
#define umpi_MPI_Ssend 1117
#define umpi_MPI_Ssend_init 1118
#define umpi_MPI_Start 1119
#define umpi_MPI_Startall 1120
#define umpi_MPI_Status_c2f 1121
#define umpi_MPI_Status_f2c 1122
#define umpi_MPI_Test 1123
#define umpi_MPI_Test_cancelled 1124
#define umpi_MPI_Testall 1125
#define umpi_MPI_Testany 1126
#define umpi_MPI_Testsome 1127
#define umpi_MPI_Topo_test 1128
#define umpi_MPI_Type_commit 1129
#define umpi_MPI_Type_contiguous 1130
#define umpi_MPI_Type_count 1131
#define umpi_MPI_Type_create_darray 1132
#define umpi_MPI_Type_create_indexed_block 1133
#define umpi_MPI_Type_create_subarray 1134
#define umpi_MPI_Type_extent 1135
#define umpi_MPI_Type_free 1136
#define umpi_MPI_Type_get_contents 1137
#define umpi_MPI_Type_get_envelope 1138
#define umpi_MPI_Type_hindexed 1139
#define umpi_MPI_Type_hvector 1140
#define umpi_MPI_Type_indexed 1141
#define umpi_MPI_Type_lb 1142
#define umpi_MPI_Type_size 1143
#define umpi_MPI_Type_struct 1144
#define umpi_MPI_Type_ub 1145
#define umpi_MPI_Type_vector 1146
#define umpi_MPI_Unpack 1147
#define umpi_MPI_Wait 1148
#define umpi_MPI_Waitall 1149
#define umpi_MPI_Waitany 1150
#define umpi_MPI_Waitsome 1151
#define umpi_MPI_Wtick 1152
#define umpi_MPI_Wtime 1153


typedef struct _umpi_mpi_lookup_t
{
char * name;
int id;
	int MPI2_function;
	int any_completion;
	int asynchronous;
	int bsend;
	int candeadlock;
	int collective;
	int comm_constructor;
	int completion;
	int group_constructor;
	int multiple_requests;
	int noasynchglobalpost;
	int noasynchglobalpre;
	int noasynchlocalpost;
	int noasynchlocalpre;
	int noasynchpost;
	int noasynchpre;
	int nolocalpost;
	int nolocalpre;
	int nonblocking;
	int nopost;
	int nopre;
	int nowrapper;
	int partial_completion;
	int persistent_init;
	int persistent_start;
	int recv;
	int request_free;
	int resource_constructor;
	int resource_destructor;
	int send;
	int sendrecv;
	int some_completion;
	int synchronous_collective;
	int test_completion;
	int type_constructor;

int (*vcode_g_pre)(umpi_op_t * op);
int (*vcode_g_post)(umpi_op_t * op);

int (*vcode_l_pre)(umpi_op_t * op);
int (*vcode_l_post)(umpi_op_t * op);
void (*print_op)(umpi_op_t * op, char *buf);
int (*pack_op)(umpi_op_t * op, char *buf, int maxlen);
int (*pack_op_size)(umpi_op_t * op);
int (*unpack_op)(umpi_op_t * op, char *buf);
void (*free_op)(umpi_op_t * op);
void (*copy_op)(umpi_op_t * op, umpi_op_t * newop);
int (*type_match_check)(umpi_matching_op_t * m_op1, umpi_matching_op_t * m_op2, int retain_type_res);
int (*local_collective_type_check)(umpi_op_t * op, int lrank);
int (*collective_type_res)(umpi_op_t * op, umpi_matching_op_t * m_op);

} umpi_mpi_lookup_t;

#define UMPI_BASE_OPCODE 1000
#define UMPI_OPCODE_COUNT 154

#endif

/*eof*/
