 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    20.74
 Total processes =                       32
 Compiled procs  =                       32
 Mop/s total     =                 24047.08
 Mop/s/process   =                   751.47
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 14:28
