 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    48.34
 Total processes =                        8
 Compiled procs  =                        8
 Mop/s total     =                 10319.86
 Mop/s/process   =                  1289.98
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              24 Jul 2014

Time = Jul 24 16:34
