 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    40.37
 Total processes =                        8
 Compiled procs  =                        8
 Mop/s total     =                 12356.02
 Mop/s/process   =                  1544.50
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 13:29
