 LU Benchmark Completed.
 Class           =                        C
 Size            =            162x 162x 162
 Iterations      =                      250
 Time in seconds =                    31.04
 Total processes =                      128
 Compiled procs  =                      128
 Mop/s total     =                 65692.75
 Mop/s/process   =                   513.22
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 12:18
real 44.258	user 41.811	sys 1.256	pcpu 97.30
