# -*- Mode: Makefile; -*-
# Makefile for conf file
#
# Main Makefile for MPI tracer.  This is all the user should really have to modify.
# TODO: maybe use autotools for all this?
#
# $Header: /home/cvs/cvs/xwu3/ScalaTraceV2/record/config/Makefile.config,v 1.1 2012/04/02 05:12:09 xwu3 Exp $

SHELL		= /bin/sh
RM		= rm -f
RANLIB		= ranlib
LEX		= flex
LEXLIB		= -lfl
YACC		= bison -y

prefix		= $(shell pwd)/../..
papiprefix = /usr/local
bindir		= ${exec_prefix}/bin
datadir		= ${prefix}/share
exec_prefix	= ${prefix}
includedir	= ${prefix}/include
infodir		= ${prefix}/info
libdir		= ${exec_prefix}/lib
libexecdir	= ${exec_prefix}/libexec
localstatedir	= ${prefix}/var
mandir		= ${prefix}/man
sbindir		= ${exec_prefix}/sbin
srcdir		= .
sysconfdir	= ${prefix}/etc
top_srcdir	= ${prefix}
papiincludedir = ${papiprefix}/include
papilibdir = ${papiprefix}/lib

ifeq ($(shell uname), AIX)
    ############################################################
    # AIX machines
    ############################################################
  platform=AIX
	YACC		= yacc

	CC= gcc
	CXX		= g++
	DEPCC           = gcc -MM
	DEPCXX          = g++ -MM
	CFLAGS= -I/usr/lpp/ppe.poe/include -DAIX
	LDFLAGS= 
	LIBS= 

	MPICC= mpcc
	MPICXX= mpCC
	MPICFLAGS   = 
	MPICXXFLAGS = 
	MPIFC  = mpf77
	MPIFCFLAGS  = 
	MPIINCLUDE= 
	MPILIBDIRS= 
	MPILIBS= 
else
ifneq ($(shell which blrts_xlc 2> /dev/null),)
    ############################################################
    # BlueGene with xlc
    ############################################################
  platform=BGL
	CC		= gcc
	CXX		= g++
	DEPCC           = gcc -MM
	DEPCXX          = g++ -MM
	CFLAGS		= -Wall -Wno-write-strings -O0 -g3 -std=gnu99
	CPPFLAGS	= 
	LDFLAGS		= 
	LIBS		= 

#	MPICC		= mpixlc
#	MPICXX		= mpixlcxx
	MPICC           = mpicc
	MPICXX          = mpicxx
#	MPICFLAGS		= -qlanglvl=extc99 -O0 -g
	MPICFLAGS		= -O0 -g -std=gnu99
	MPICXXFLAGS =
  MPIFC  = mpif77
  MPIFCFLAGS  = 
	MPIINCLUDE	= 
	MPILIBDIRS	= 
	MPILIBS		= 
    ############################################################
else
    ############################################################
    # x86_64 machines with gcc
    ############################################################
  platform=X86_64
#	CC		= gcc
#	CXX		= g++
#	DEPCC           = gcc -MM
#	DEPCXX          = g++ -MM
#	CFLAGS		= -Wall -Wno-write-strings -O3 -g3 -std=gnu99 -fno-omit-frame-pointer
#	CXXFLAGS	= -Wall -Wno-write-strings -O3 -g3 -fno-omit-frame-pointer

	CC		= gcc
	CXX		= g++
	DEPCC           = gcc -MM
	DEPCXX          = g++ -MM
	CFLAGS		= -Wno-write-strings -O0 -g -std=gnu99 -fno-omit-frame-pointer
	CXXFLAGS	= -Wno-write-strings -O0 -g -fno-omit-frame-pointer


	CPPFLAGS	=
	LDFLAGS		= 
	LIBS		= 

	MPICC		= mpicc 
	MPICXX		= mpicxx
	MPICFLAGS   = $(CFLAGS)
	MPICXXFLAGS = $(CXXFLAGS) -DMPICH_SKIP_MPICXX
	MPICPPFLAGS = 
  MPIFC = mpif77
  MPIFCFLAGS  = 
	MPIINCLUDE	= 
	MPILIBDIRS	= 
	MPILIBS		= 
    ############################################################
endif
endif

# Check for presence of "indent"
ifneq ($(shell which indent 2> /dev/null),)
CONFIG_HAVE_INDENT:=y
else
CONFIG_HAVE_INDENT:=n
endif


##### EOF
