 LU Benchmark Completed.
 Class           =                        C
 Size            =            162x 162x 162
 Iterations      =                      250
 Time in seconds =                    38.46
 Total processes =                       64
 Compiled procs  =                       64
 Mop/s total     =                 53014.69
 Mop/s/process   =                   828.35
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 12:23
real 44.574	user 43.195	sys 0.832	pcpu 98.77
