 LU Benchmark Completed.
 Class           =                        C
 Size            =            162x 162x 162
 Iterations      =                      250
 Time in seconds =                    86.16
 Total processes =                       16
 Compiled procs  =                       16
 Mop/s total     =                 23666.15
 Mop/s/process   =                  1479.13
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 16:10
