 LU Benchmark Completed.
 Class           =                        C
 Size            =            162x 162x 162
 Iterations      =                      250
 Time in seconds =                   140.83
 Total processes =                        8
 Compiled procs  =                        8
 Mop/s total     =                 14477.95
 Mop/s/process   =                  1809.74
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 16:24
