 LU Benchmark Completed.
 Class           =                        A
 Size            =             64x  64x  64
 Iterations      =                      250
 Time in seconds =                    17.81
 Total processes =                        4
 Compiled procs  =                        4
 Mop/s total     =                  6697.92
 Mop/s/process   =                  1674.48
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 16:29
