 LU Benchmark Completed.
 Class           =                        C
 Size            =            162x 162x 162
 Iterations      =                      250
 Time in seconds =                    36.39
 Total processes =                       64
 Compiled procs  =                       64
 Mop/s total     =                 56034.74
 Mop/s/process   =                   875.54
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 11:03
real 42.192	user 41.207	sys 0.432	pcpu 98.68
