 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    65.57
 Total processes =                        4
 Compiled procs  =                        4
 Mop/s total     =                  7607.26
 Mop/s/process   =                  1901.82
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 14:45
