 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    22.07
 Total processes =                       32
 Compiled procs  =                       32
 Mop/s total     =                 22598.51
 Mop/s/process   =                   706.20
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 13:19
