 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    31.53
 Total processes =                       16
 Compiled procs  =                       16
 Mop/s total     =                 15821.00
 Mop/s/process   =                   988.81
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              24 Jul 2014

Time = Jul 24 10:48
