 LU Benchmark Completed.
 Class           =                        A
 Size            =             64x  64x  64
 Iterations      =                      250
 Time in seconds =                     8.87
 Total processes =                       64
 Compiled procs  =                       64
 Mop/s total     =                 13442.24
 Mop/s/process   =                   210.04
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 12:44
real 12.415	user 11.209	sys 0.432	pcpu 93.77
