 LU Benchmark Completed.
 Class           =                        A
 Size            =             64x  64x  64
 Iterations      =                      250
 Time in seconds =                     9.98
 Total processes =                       16
 Compiled procs  =                       16
 Mop/s total     =                 11951.92
 Mop/s/process   =                   746.99
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 14:52
