 LU Benchmark Completed.
 Class           =                        A
 Size            =             64x  64x  64
 Iterations      =                      250
 Time in seconds =                     8.14
 Total processes =                      128
 Compiled procs  =                      128
 Mop/s total     =                 14656.95
 Mop/s/process   =                   114.51
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 12:01
real 14.628	user 12.877	sys 0.672	pcpu 92.62
