 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    39.49
 Total processes =                        8
 Compiled procs  =                        8
 Mop/s total     =                 12631.58
 Mop/s/process   =                  1578.95
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 14:37
