/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Sun Jul 23 16:03:31 2000
 */
/* BRONIS: I edited it anyway; DON'T REEXTRACT... */

#ifndef __CEXTRACT__
#if __STDC__

extern Q_t *q_open (void);
extern int q_close (Q_t * q);

#ifndef UMPI_HAND_INLINING
extern int q_empty (Q_t * q);
extern int q_count (Q_t * q);
extern int q_append (Q_t * q, void *data);
extern void *q_head (Q_t * q);
extern void *q_tail (Q_t * q);
#endif
extern int q_enqueue (Q_t * q, void *data);
extern int q_dequeue (Q_t * q, void **data);

extern int q_replace (Q_t * q, qComparator comp, void *oldkey, void *newkey,
		      void **data);
extern int q_search (Q_t * q, qComparator comp, void *key, void **data);
extern int q_search_ele (Q_t * q, qComparator comp, void *key,
			 Q_ele_t ** ele);
extern int q_delete (Q_t * q, qComparator comp, void *key, void **data);
extern void q_push (Q_t * q, void *data);
extern int q_pop (Q_t * q, void **data);
extern int q_insert (Q_t * q, qComparator comp, void *data);
extern void *q_next (Q_t * q, Q_ele_t * e);
extern void *q_prev (Q_t * q, Q_ele_t * e);
extern int q_walk (Q_t * q, qApply apply);
extern int q_iterate (Q_t * q, qApplyWithArg apply, void *arg, int base_res);
extern int q_range_iterate (Q_t * q, qApplyWithArg apply, 
			    void *arg, int base_res, 
			    int start, int stop, int step);
extern int _q_remove (Q_t * q, Q_ele_t *e); 
extern int _q_walk (Q_t * q, _qApply apply);

#else /* __STDC__ */

extern Q_t *q_open ( /* void */ );
extern int q_close ( /* Q_t * q */ );

#ifndef UMPI_HAND_INLINING
extern int q_empty ( /* Q_t * q */ );
extern int q_count ( /* Q_t * q */ );
extern int q_append ( /* Q_t * q, void *data */ );
extern void *q_head ( /* Q_t * q */ );
extern void *q_tail ( /* Q_t * q */ );
#endif
extern int q_enqueue ( /* Q_t * q, void *data */ );
extern int q_dequeue ( /* Q_t * q, void **data */ );

extern int q_replace (
		      /* Q_t * q, qComparator comp, void *oldkey, void *newkey, void **data */
		      );
extern int q_search ( /* Q_t * q, qComparator comp, void *key, void **data */
		     );
extern int q_search_ele (
			 /* Q_t * q, qComparator comp, void *key, Q_ele_t **ele */
			 );
extern int q_delete ( /* Q_t * q, qComparator comp, void *key, void **data */
		     );
extern int q_push ( /* Q_t * q, void *data */ );
extern int q_pop ( /* Q_t * q, void **data */ );
extern int q_insert ( /* Q_t * q, qComparator comp, void *data */ );
extern void *q_next ( /* Q_t * q, Q_ele_t * e */ );
extern void *q_prev ( /* Q_t * q, Q_ele_t * e */ );
extern int q_walk ( /* Q_t * q, qApply apply */ );
extern int q_iterate ( /* Q_t * q, qApplyWithArg apply, void *arg, int base_res */ );
extern int q_range_iterate ( /* Q_t * q, qApplyWithArg apply, 
				void *arg, int base_res, 
				int start, int stop, int step */ );
extern _q_remove ( /* Q_t * q, Q_ele_t *e */ ); 
extern int _q_walk ( /* Q_t * q, _qApply apply */ );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
