 LU Benchmark Completed.
 Class           =                        C
 Size            =            162x 162x 162
 Iterations      =                      250
 Time in seconds =                   232.42
 Total processes =                        8
 Compiled procs  =                        8
 Mop/s total     =                  8772.83
 Mop/s/process   =                  1096.60
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              24 Jul 2014

Time = Jul 24 16:17
