 LU Benchmark Completed.
 Class           =                        C
 Size            =            162x 162x 162
 Iterations      =                      250
 Time in seconds =                    28.35
 Total processes =                      128
 Compiled procs  =                      128
 Mop/s total     =                 71919.29
 Mop/s/process   =                   561.87
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 10:56
real 40.431	user 38.374	sys 0.712	pcpu 96.67
