 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    15.75
 Total processes =                       64
 Compiled procs  =                       64
 Mop/s total     =                 31671.46
 Mop/s/process   =                   494.87
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 11:56
real 19.924	user 19.029	sys 0.324	pcpu 97.14
