 LU Benchmark Completed.
 Class           =                        A
 Size            =             64x  64x  64
 Iterations      =                      250
 Time in seconds =                     9.98
 Total processes =                       32
 Compiled procs  =                       32
 Mop/s total     =                 11958.14
 Mop/s/process   =                   373.69
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 13:45
