 LU Benchmark Completed.
 Class           =                        C
 Size            =            162x 162x 162
 Iterations      =                      250
 Time in seconds =                    57.66
 Total processes =                       32
 Compiled procs  =                       32
 Mop/s total     =                 35365.32
 Mop/s/process   =                  1105.17
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 13:11
