 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    17.00
 Total processes =                       64
 Compiled procs  =                       64
 Mop/s total     =                 29338.53
 Mop/s/process   =                   458.41
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 12:37
real 21.647	user 20.309	sys 0.540	pcpu 96.31
