 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    66.19
 Total processes =                        4
 Compiled procs  =                        4
 Mop/s total     =                  7536.71
 Mop/s/process   =                  1884.18
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 13:36
