 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    14.50
 Total processes =                      128
 Compiled procs  =                      128
 Mop/s total     =                 34404.83
 Mop/s/process   =                   268.79
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 11:50
real 23.365	user 20.985	sys 0.804	pcpu 93.26
