 LU Benchmark Completed.
 Class           =                        C
 Size            =            162x 162x 162
 Iterations      =                      250
 Time in seconds =                   256.74
 Total processes =                        4
 Compiled procs  =                        4
 Mop/s total     =                  7941.72
 Mop/s/process   =                  1985.43
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 14:19
