 LU Benchmark Completed.
 Class           =                        A
 Size            =             64x  64x  64
 Iterations      =                      250
 Time in seconds =                     9.19
 Total processes =                       32
 Compiled procs  =                       32
 Mop/s total     =                 12982.80
 Mop/s/process   =                   405.71
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 14:49
