 LU Benchmark Completed.
 Class           =                        B
 Size            =            102x 102x 102
 Iterations      =                      250
 Time in seconds =                    15.83
 Total processes =                      128
 Compiled procs  =                      128
 Mop/s total     =                 31507.93
 Mop/s/process   =                   246.16
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 12:33
real 25.348	user 22.901	sys 0.968	pcpu 94.17
