 LU Benchmark Completed.
 Class           =                        A
 Size            =             64x  64x  64
 Iterations      =                      250
 Time in seconds =                     8.14
 Total processes =                       64
 Compiled procs  =                       64
 Mop/s total     =                 14647.60
 Mop/s/process   =                   228.87
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              30 Jul 2014

Time = Jul 30 12:06
real 11.315	user 10.377	sys 0.300	pcpu 94.36
