 LU Benchmark Completed.
 Class           =                        C
 Size            =            162x 162x 162
 Iterations      =                      250
 Time in seconds =                   139.39
 Total processes =                        8
 Compiled procs  =                        8
 Mop/s total     =                 14627.84
 Mop/s/process   =                  1828.48
 Operation type  =           floating point
 Verification    =               SUCCESSFUL
 Version         =                      3.3
 Compile date    =              29 Jul 2014

Time = Jul 29 15:30
